---
vlans:
  - vlan_id: 10
    name: to-rtr1
    state: active
    shutdown: disabled
    mtu: 1500
  - vlan_id: 20
    name: users
    state: active
    shutdown: disabled 
    mtu: 1500
  - vlan_id: 30
    name: servers
    state: active
    shutdown: disabled
    mtu: 1500
  # - vlan_id: 31
  #   name: new_servers
  #   state: active 
  #   shutdown: disabled
  #   mtu: 1500
  - vlan_id: 40
    name: mgmt
    state: active
    shutdown: disabled
    mtu: 1500

  # default vlans
  - vlan_id: 1
    name: default
    state: active
    shutdown: disabled
    mtu: 1500
  - vlan_id: 1002
    name: fddi-default
    state: active
    shutdown: enabled
    mtu: 1500 
  - vlan_id: 1003
    name: token-ring-default
    state: active
    shutdown: enabled
    mtu: 1500
  - vlan_id: 1004
    name: fddinet-default
    state: active
    shutdown: enabled
    mtu: 1500
  - vlan_id: 1005
    name: trnet-default
    state: active
    shutdown: enabled
    mtu: 1500