---
vlans:
  - vlan_id: 10
    name: to-rtr1
    state: active
    shutdown: disabled
    mtu: 1500
  - vlan_id: 20
    name: users
    state: active
    shutdown: disabled
    mtu: 1500
  - vlan_id: 30
    name: servers
    state: active
    shutdown: disabled
    mtu: 1500
  # - vlan_id: 31
  #   name: new_servers
  #   state: active
  #   shutdown: disabled
  #   mtu: 1500
  - vlan_id: 40
    name: mgmt
    state: active
    shutdown: disabled
    mtu: 1500