---
interfaces:
  - name: Loopback0
    description: loopback
    ipv4:
      - address: 1.1.1.1/32
    enabled: true
    state: present
  - name: Ethernet0/1
    description: to-rtr2
    ipv4:
      - address: 10.0.0.3/30
    enabled: true
    state: present
  - name: Ethernet0/2
    description: to-sw1
    ipv4:
      - address: 192.168.1.1/24
    enabled: true
    state: present

