---
compliance_report_dir: /tmp/compliance_reports

# What checks you want to show in the report
# key must match result variable naming: <prefix>_<key>_result
compliance_checks:
  - label: VLANs
    key: vlan
  - label: L2 Interfaces
    key: l2_interfaces
  - label: Interfaces
    key: interfaces
  - label: L3 Interfaces
    key: l3_interfaces

# Map platform -> result variable prefix (arista_* vs cisco_*)
platform_result_prefix:
  eos: arista
  ios-xe: cisco
