---
vlans:
  - vlan_id: 10
    name: to-rtr1
    state: present
  - vlan_id: 20
    name: users
    state: present
  - vlan_id: 30
    name: servers
    state: present
  - vlan_id: 40
    name: mgmt
    state: present

  # #default vlans
  # - vlan_id: 1
  #   state: present
  # - vlan_id: 1002
  #   state: present
  # - vlan_id: 1003
  #   state: present
  # - vlan_id: 1004
  #   state: present
  # - vlan_id: 1005
  #   state: present